apiVersion: v2
name: event-exporter
description: Export kubernetes events to stdout so that we can ship them to Loki
version: 0.0.2
dependencies:
  - name: kubernetes-event-exporter
    version: 2.10.0
    repository: https://charts.bitnami.com/bitnami
